### ISSUE TITLE
HTTP Error 404 when closing a Cursor

### ISSUE THREAD

**Issue by gioruss** [trinodb/trino-python-client#289]
### Expected behavior

When calling the method `close` on a `Cursor` only running queries should be cancelled.

### Actual behavior

When calling the method `close` on a `Cursor` an attempt is made to clear the last submitted query.
This behaviour was introduced with this commit: https://github.com/trinodb/trino-python-client/commit/ed2203f09935f26fc65df23ab8ef79655e0eecc5
It seems that when the last query is already finished the Trino server returns a 404 error and this causes a failure to close the cursor.

### Steps To Reproduce

Environment:

- Trino >= 400
- Apache Superset 1.5.2
- Trino python client >= 0.315.0

To reproduce the issue simply use the Superset SQL Editor and try to refresh the schemas list inside any Trino catalog.

### Log output
```
2022-11-17 11:23:39,547:DEBUG:urllib3.connectionpool:http://localhost:9090 "DELETE /v1/query/20221117_112338_00001_gpxh7 HTTP/1.1" 404 0
2022-11-17 11:23:39,547:ERROR:root:error 404
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 155, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/views/base_api.py", line 112, in wraps
    raise ex
  File "/app/superset/views/base_api.py", line 109, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/app/superset/utils/core.py", line 1483, in time_function
    response = func(*args, **kwargs)
  File "/app/superset/utils/log.py", line 245, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/databases/api.py", line 457, in schemas
    schemas = database.get_all_schema_names(
  File "/app/superset/utils/cache.py", line 119, in wrapped_f
    return f(self, *args, **kwargs)
  File "/app/superset/models/core.py", line 639, in get_all_schema_names
    return self.db_engine_spec.get_schema_names(self.inspector)
  File "/app/superset/models/core.py", line 523, in inspector
    return sqla.inspect(engine)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/inspection.py", line 64, in inspect
    ret = reg(subject)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 139, in _insp
    return Inspector.from_engine(bind)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 135, in from_engine
    return Inspector(bind)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/reflection.py", line 108, in __init__
    bind.connect().close()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
    return self._wrap_pool_connect(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 664, in __connect
    pool.dispatch.first_connect.for_modify(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 314, in exec_once_unless_exception
    self._exec_once_impl(True, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 285, in _exec_once_impl
    self(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1406, in go
    return once_fn(*arg, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 199, in first_connect
    dialect.initialize(c)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 330, in initialize
    self.returns_unicode_strings = self._check_unicode_returns(connection)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 433, in _check_unicode_returns
    results = {check_unicode(test) for test in tests}
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 433, in <setcomp>
    results = {check_unicode(test) for test in tests}
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 404, in check_unicode
    cursor.close()
  File "/usr/local/lib/python3.8/site-packages/trino/dbapi.py", line 530, in close
    self.cancel()
  File "/usr/local/lib/python3.8/site-packages/trino/dbapi.py", line 527, in cancel
    self._query.cancel()
  File "/usr/local/lib/python3.8/site-packages/trino/client.py", line 798, in cancel
    self._request.raise_response_error(response)
  File "/usr/local/lib/python3.8/site-packages/trino/client.py", line 559, in raise_response_error
    raise exceptions.HttpError(
trino.exceptions.HttpError: error 404
```

### Operating System

Debian GNU/Linux 11 (bullseye)

### Trino Python client version

0.318.0

### Trino Server version

402

### Python version

3.8.13

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hovaesco** [comment]
Could you please provide a simple script to reproduce the issue?

**Comment by hashhar** [comment]
Fixed by https://github.com/trinodb/trino-python-client/pull/328
